import assert from 'node:assert/strict';
import http from 'node:http';
import test from 'node:test';
import { createApp } from '../../src/app.js';
import { createLogger } from '../../src/config/logger.js';
import { AuthenticationError, ConflictError, NotFoundError } from '../../src/errors/application-error.js';
import { hashOpaqueToken } from '../../src/lib/crypto/opaque-token.js';

const A='aaaaaaaaaaaaaaaaaaaaaaaa',B='bbbbbbbbbbbbbbbbbbbbbbbb',GIG='cccccccccccccccccccccccc',SKILL='dddddddddddddddddddddddd';
const csrfSecret='test-csrf-secret-with-more-than-thirty-two-characters';
const config={nodeEnv:'test',clientUrl:'http://localhost:5173',trustProxy:false,isProduction:false,sessionCookieName:'campuscollab_session',sessionSecret:'test-session-secret-with-more-than-thirty-two-characters',csrfSecret,smtp:null,requireEmailVerification:false};
const logger=createLogger({level:'silent',environment:'test'});
const authService={async authenticate(token){if(!token)throw new AuthenticationError();return{user:{_id:token==='b-token'?B:A},session:{_id:GIG}}}};
const gig={id:GIG,title:'Build the campus society website',description:'Create an accessible responsive site for student society events.',category:'Web Development',skills:[{id:SKILL,name:'React',level:'INTERMEDIATE',required:true}],workMode:'REMOTE',locationText:'',visibility:'PLATFORM',budget:{type:'UNPAID'},deadlineAt:null,capacity:1,acceptedCount:0,proposalCount:0,acceptingProposals:false,status:'DRAFT',owner:{id:A,displayName:'Owner A'},isOwner:true,isBookmarked:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
function fakeService(calls){return{async create(id,body){calls.push(['create',String(id),body]);return gig},async list(query,id){calls.push(['list',query,String(id||'')]);return{gigs:[{...gig,status:'PUBLISHED',isOwner:false}],nextCursor:'next',hasMore:true}},async mine(id,query){calls.push(['mine',String(id),query]);return{gigs:[gig],nextCursor:null,hasMore:false}},async get(id,viewer){calls.push(['get',id,String(viewer||'')]);if(id===B||String(viewer)===B)throw new NotFoundError();return gig},async update(id,gigId,body){calls.push(['update',String(id),gigId,body]);if(String(id)===B)throw new NotFoundError();return{...gig,...body}},async transition(id,gigId,action){calls.push(['transition',String(id),gigId,action]);if(String(id)===B)throw new NotFoundError();if(action==='publish'&&gig.status!=='DRAFT')throw new ConflictError('INVALID_STATE');return{...gig,status:'PUBLISHED'}},async remove(id,gigId){calls.push(['remove',String(id),gigId]);if(String(id)===B)throw new NotFoundError()},async addBookmark(id,gigId){calls.push(['bookmark',String(id),gigId]);return{created:!calls.some((entry,index)=>entry[0]==='bookmark'&&index<calls.length-1),bookmark:{gigId}}},async removeBookmark(id,gigId){calls.push(['unbookmark',String(id),gigId])},async bookmarks(id){calls.push(['bookmarks',String(id)]);return{gigs:[{...gig,isBookmarked:true}],nextCursor:null,hasMore:false}}}};
async function withServer(work){const calls=[];const app=createApp({config,logger,databaseReadiness:()=>({ready:true}),authService,gigService:fakeService(calls)});const server=http.createServer(app);await new Promise((resolve)=>server.listen(0,'127.0.0.1',resolve));try{await work(`http://127.0.0.1:${server.address().port}`,calls)}finally{await new Promise((resolve)=>server.close(resolve))}}
function headers(token='a-token',json=false){return{cookie:`campuscollab_session=${token}`,...json?{'x-csrf-token':hashOpaqueToken(token,csrfSecret),'content-type':'application/json'}:{}}}
const valid={title:gig.title,description:gig.description,category:gig.category,skillRequirements:[{skillId:SKILL,level:'INTERMEDIATE',required:true}],workMode:'REMOTE',visibility:'PLATFORM',budget:{type:'UNPAID'},capacity:1};

test('gig discovery is public, server-filtered, and cursor paginated',()=>withServer(async(base,calls)=>{const response=await fetch(`${base}/api/v1/gigs?q=campus&workMode=REMOTE&limit=5`);assert.equal(response.status,200);const body=await response.json();assert.equal(body.data.gigs.length,1);assert.equal(body.meta.pagination.nextCursor,'next');assert.equal(calls.at(-1)[0],'list');assert.equal(calls.at(-1)[1].q,'campus')}));
test('authenticated user creates a draft from session identity',()=>withServer(async(base,calls)=>{assert.equal((await fetch(`${base}/api/v1/gigs`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(valid)})).status,401);const response=await fetch(`${base}/api/v1/gigs`,{method:'POST',headers:headers('a-token',true),body:JSON.stringify(valid)});assert.equal(response.status,201);assert.deepEqual(calls.at(-1).slice(0,2),['create',A])}));
test('gig validation rejects invalid fields, ownership spoofing, roles, capabilities, and lifecycle state',()=>withServer(async(base,calls)=>{const invalid=await fetch(`${base}/api/v1/gigs`,{method:'POST',headers:headers('a-token',true),body:JSON.stringify({...valid,title:'x'})});assert.equal(invalid.status,422);for(const injected of [{ownerId:B},{userId:B},{status:'PUBLISHED'},{role:'ADMIN'},{capabilities:['ADMIN']}]){const spoof=await fetch(`${base}/api/v1/gigs`,{method:'POST',headers:headers('a-token',true),body:JSON.stringify({...valid,...injected})});assert.equal(spoof.status,422)}assert.equal(calls.length,0)}));
test('owner update uses authenticated identity and non-owner is concealed',()=>withServer(async(base,calls)=>{const owner=await fetch(`${base}/api/v1/gigs/${GIG}`,{method:'PATCH',headers:headers('a-token',true),body:JSON.stringify({title:'Updated campus opportunity'})});assert.equal(owner.status,200);assert.deepEqual(calls.at(-1).slice(0,3),['update',A,GIG]);const other=await fetch(`${base}/api/v1/gigs/${GIG}`,{method:'PATCH',headers:headers('b-token',true),body:JSON.stringify({title:'Stolen campus opportunity'})});assert.equal(other.status,404)}));
test('gig detail requires login, conceals non-owned private gigs, and validates identifiers',()=>withServer(async(base)=>{assert.equal((await fetch(`${base}/api/v1/gigs/${GIG}`)).status,401);assert.equal((await fetch(`${base}/api/v1/gigs/${GIG}`,{headers:headers('a-token')})).status,200);assert.equal((await fetch(`${base}/api/v1/gigs/${GIG}`,{headers:headers('b-token')})).status,404);assert.equal((await fetch(`${base}/api/v1/gigs/not-an-id`,{headers:headers('a-token')})).status,422)}));
test('lifecycle command and unknown field validation protect status',()=>withServer(async(base,calls)=>{const publish=await fetch(`${base}/api/v1/gigs/${GIG}:publish`,{method:'POST',headers:headers('a-token',true),body:'{}'});assert.equal(publish.status,200);assert.equal(calls.at(-1)[3],'publish');const direct=await fetch(`${base}/api/v1/gigs/${GIG}`,{method:'PATCH',headers:headers('a-token',true),body:JSON.stringify({status:'PUBLISHED'})});assert.equal(direct.status,422)}));
test('User B cannot change User A gig lifecycle',()=>withServer(async(base)=>{const response=await fetch(`${base}/api/v1/gigs/${GIG}:publish`,{method:'POST',headers:headers('b-token',true),body:'{}'});assert.equal(response.status,404)}));
test('permanent delete requires authentication, CSRF, and owner identity',()=>withServer(async(base,calls)=>{assert.equal((await fetch(`${base}/api/v1/gigs/${GIG}`,{method:'DELETE'})).status,401);const owner=await fetch(`${base}/api/v1/gigs/${GIG}`,{method:'DELETE',headers:headers('a-token',true)});assert.equal(owner.status,204);assert.deepEqual(calls.at(-1),['remove',A,GIG]);const other=await fetch(`${base}/api/v1/gigs/${GIG}`,{method:'DELETE',headers:headers('b-token',true)});assert.equal(other.status,404)}));
test('bookmarks require authentication, prevent duplicate creation, and remove idempotently',()=>withServer(async(base)=>{assert.equal((await fetch(`${base}/api/v1/gigs/${GIG}/bookmark`,{method:'POST'})).status,401);const first=await fetch(`${base}/api/v1/gigs/${GIG}/bookmark`,{method:'POST',headers:headers('a-token',true)});const firstBody=await first.text();assert.equal(first.status,201,firstBody);const remove=await fetch(`${base}/api/v1/gigs/${GIG}/bookmark`,{method:'DELETE',headers:headers('a-token',true)});assert.equal(remove.status,204);const list=await fetch(`${base}/api/v1/users/me/bookmarked-gigs`,{headers:headers()});assert.equal(list.status,200)}));
test('MongoDB operators and duplicate query parameters are rejected before service access',()=>withServer(async(base)=>{const unsafe=await fetch(`${base}/api/v1/gigs`,{method:'POST',headers:headers('a-token',true),body:JSON.stringify({...valid,budget:{$ne:null}})});assert.equal(unsafe.status,400);const duplicate=await fetch(`${base}/api/v1/gigs?sort=NEWEST&sort=DEADLINE`);assert.equal(duplicate.status,400)}));
