import { Bookmark, Search } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { GigCard } from '../components/gigs/GigCard.jsx';
import { useToast } from '../context/toast-context.js';
import { AppShell } from '../layouts/AppShell.jsx';
import { apiError, gigApi } from '../services/api.js';

export function BookmarksPage(){const {notify}=useToast();const [gigs,setGigs]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [pagination,setPagination]=useState({});const [busy,setBusy]=useState('');const load=useCallback(async(cursor,append=false)=>{append||setLoading(true);try{const response=await gigApi.bookmarks(cursor?{cursor}:{});setGigs((current)=>append?[...current,...response.data.data.gigs]:response.data.data.gigs);setPagination(response.data.meta.pagination);setError('')}catch(reason){setError(apiError(reason).message)}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const remove=async(gig)=>{setBusy(gig.id);try{await gigApi.removeBookmark(gig.id);setGigs((current)=>current.filter((item)=>item.id!==gig.id));notify('Bookmark removed.')}catch(reason){notify(apiError(reason).message,'error')}finally{setBusy('')}};return <AppShell><div><p className="eyebrow">Saved opportunities</p><h1 className="mt-2 text-3xl font-bold">Bookmarks</h1><p className="mt-2 text-slate-600">Keep promising opportunities within reach.</p>{loading?<div className="mt-7 h-80 animate-pulse rounded-2xl bg-slate-200"/>:error?<div className="surface mt-7 p-8 text-center"><p>{error}</p><button className="btn-primary mt-4" onClick={()=>load()}>Try again</button></div>:gigs.length===0?<div className="surface mt-7 p-10 text-center"><Bookmark className="mx-auto text-slate-400"/><h2 className="mt-4 text-xl font-bold">No bookmarked gigs</h2><p className="mt-2 text-slate-600">Save opportunities from the marketplace to find them here.</p><Link className="btn-primary mt-5" to="/gigs"><Search size={17}/>Discover gigs</Link></div>:<><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{gigs.map((gig)=><GigCard key={gig.id} gig={gig} busy={busy===gig.id} onBookmark={remove}/>)}</div>{pagination.hasMore&&<div className="mt-7 text-center"><button className="btn-secondary" onClick={()=>load(pagination.nextCursor,true)}>Load more</button></div>}</>}</div></AppShell>}
