import { AlertCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { GigForm } from '../components/gigs/GigForm.jsx';
import { useToast } from '../context/toast-context.js';
import { AppShell } from '../layouts/AppShell.jsx';
import { apiError, gigApi, skillApi } from '../services/api.js';

export function GigFormPage(){const {gigId}=useParams();const editing=Boolean(gigId);const navigate=useNavigate();const {notify}=useToast();const [gig,setGig]=useState(null);const [skills,setSkills]=useState([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');useEffect(()=>{let active=true;Promise.all([skillApi.list(),...(editing?[gigApi.get(gigId)]:[])]).then(([skillResponse,gigResponse])=>{if(!active)return;setSkills(skillResponse.data.data.skills);if(editing){if(!gigResponse.data.data.gig.isOwner)throw Object.assign(new Error('Forbidden'),{response:{status:403,data:{error:{message:'Only the owner can edit this gig.'}}}});setGig(gigResponse.data.data.gig)}}).catch((reason)=>setError(apiError(reason).message)).finally(()=>setLoading(false));return()=>{active=false}},[editing,gigId]);const createSkill=async(body)=>{try{const skill=(await skillApi.create(body)).data.data.skill;setSkills((current)=>current.some((item)=>item.id===skill.id)?current:[...current,skill].sort((a,b)=>a.name.localeCompare(b.name)));notify('Skill added and selected.');return skill}catch(reason){notify(apiError(reason).message,'error');return null}};const submit=async(body)=>{setSaving(true);try{const result=editing?(await gigApi.update(gigId,body)).data.data.gig:(await gigApi.create(body)).data.data.gig;notify(editing?'Gig updated.':'Gig draft created.');navigate(`/gigs/${result.id}`)}catch(reason){notify(apiError(reason).message,'error')}finally{setSaving(false)}};return <AppShell><div className="mx-auto max-w-4xl"><Link className="text-sm font-bold text-brand-700" to={editing?`/gigs/${gigId}`:'/my-gigs'}>← Back</Link><p className="eyebrow mt-6">Gig owner workspace</p><h1 className="mt-2 text-3xl font-bold">{editing?'Edit gig':'Create a gig'}</h1><p className="mt-2 text-slate-600">{editing?'Update only the terms that remain editable in this lifecycle state.':'Create a clear draft, review it, then publish it from My Gigs.'}</p>{loading?<div className="mt-7 h-96 animate-pulse rounded-3xl bg-slate-200"/>:error?<div className="surface mt-7 p-8 text-center"><AlertCircle className="mx-auto text-rose-600"/><p className="mt-3 font-semibold">{error}</p></div>:<div className="mt-7"><GigForm initial={gig} skills={skills} saving={saving} onSubmit={submit} onCreateSkill={createSkill}/></div>}</div></AppShell>}
