import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { AuthContext } from '../context/auth-context.js';
import { ToastContext } from '../context/toast-context.js';
import { ProtectedRoute } from '../routes/RouteGuards.jsx';
import { GigDetailsPage } from './GigDetailsPage.jsx';
import { GigFormPage } from './GigFormPage.jsx';
import { GigsPage } from './GigsPage.jsx';

const mocks=vi.hoisted(()=>({list:vi.fn(),get:vi.fn(),create:vi.fn(),update:vi.fn(),bookmark:vi.fn(),removeBookmark:vi.fn(),skills:vi.fn(),notify:vi.fn()}));
vi.mock('../services/api.js',()=>({gigApi:{list:mocks.list,get:mocks.get,create:mocks.create,update:mocks.update,bookmark:mocks.bookmark,removeBookmark:mocks.removeBookmark},skillApi:{list:mocks.skills},apiError:(error)=>({status:error?.response?.status,message:error?.message||'Request failed'})}));
const skill={id:'dddddddddddddddddddddddd',name:'React',category:'Frontend'};
const gig={id:'cccccccccccccccccccccccc',title:'Build the campus society website',description:'Create an accessible responsive site for student society events.',category:'Web Development',skills:[{...skill,level:'INTERMEDIATE',required:true}],workMode:'REMOTE',locationText:'',visibility:'PLATFORM',budget:{type:'UNPAID'},deadlineAt:null,capacity:1,acceptedCount:0,proposalCount:0,acceptingProposals:true,status:'PUBLISHED',owner:{id:'aaaaaaaaaaaaaaaaaaaaaaaa',displayName:'Sristi Kundu'},isOwner:false,isBookmarked:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
const auth={loading:false,isAuthenticated:true,user:{email:'student@bscse.uiu.ac.bd',profile:{displayName:'Student'}},logout:vi.fn()};
const response=(data,meta={})=>Promise.resolve({data:{data,meta}});
function renderAt(ui,path='/gigs',value=auth){return render(<MemoryRouter initialEntries={[path]}><AuthContext.Provider value={value}><ToastContext.Provider value={{notify:mocks.notify}}>{ui}</ToastContext.Provider></AuthContext.Provider></MemoryRouter>)}
beforeEach(()=>{mocks.list.mockImplementation(()=>response({gigs:[gig]},{pagination:{nextCursor:null,hasMore:false}}));mocks.get.mockImplementation(()=>response({gig}));mocks.skills.mockImplementation(()=>response({skills:[skill]}));mocks.create.mockImplementation((body)=>response({gig:{...gig,...body,status:'DRAFT'}}));mocks.update.mockImplementation((_,body)=>response({gig:{...gig,...body,isOwner:true}}));mocks.bookmark.mockResolvedValue({});mocks.removeBookmark.mockResolvedValue({})});afterEach(()=>{cleanup();vi.clearAllMocks()});

describe('Gigs Marketplace',()=>{
  it('renders server-provided gig cards',async()=>{renderAt(<GigsPage/>);expect(await screen.findByText(gig.title)).toBeInTheDocument();expect(screen.getAllByText('React').length).toBeGreaterThan(0);expect(screen.getByText('Sristi Kundu')).toBeInTheDocument()});
  it('sends search and filters to the backend',async()=>{const user=userEvent.setup();renderAt(<GigsPage/>);await screen.findByText(gig.title);await user.type(screen.getByLabelText('Search gigs'),'dashboard');await user.selectOptions(screen.getByLabelText('Skill filter'),skill.id);await user.selectOptions(screen.getByLabelText('Work mode filter'),'REMOTE');await user.click(screen.getByRole('button',{name:'Apply filters'}));await waitFor(()=>expect(mocks.list).toHaveBeenLastCalledWith(expect.objectContaining({q:'dashboard',skillId:skill.id,workMode:'REMOTE'})))});
  it('bookmarks a gig and updates the visible state',async()=>{const user=userEvent.setup();renderAt(<GigsPage/>);await screen.findByText(gig.title);await user.click(screen.getByRole('button',{name:'Bookmark gig'}));await waitFor(()=>expect(mocks.bookmark).toHaveBeenCalledWith(gig.id));expect(screen.getByRole('button',{name:'Remove bookmark'})).toBeInTheDocument()});
  it('shows empty and retryable API error states',async()=>{mocks.list.mockImplementationOnce(()=>response({gigs:[]},{pagination:{hasMore:false}}));const first=renderAt(<GigsPage/>);expect(await screen.findByText('No opportunities found.')).toBeInTheDocument();first.unmount();mocks.list.mockRejectedValueOnce(new Error('Marketplace unavailable'));renderAt(<GigsPage/>);expect(await screen.findByText('Marketplace unavailable')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Try again'})).toBeInTheDocument()});
  it('renders gig details and keeps proposal functionality disabled',async()=>{renderAt(<Routes><Route path="/gigs/:gigId" element={<GigDetailsPage/>}/></Routes>,`/gigs/${gig.id}`);expect(await screen.findByRole('heading',{name:gig.title})).toBeInTheDocument();expect(screen.getByText(/About this gig/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Apply to this Gig'})).toBeDisabled()});
  it('validates the create form before calling the API',async()=>{const user=userEvent.setup();renderAt(<Routes><Route path="/gigs/new" element={<GigFormPage/>}/></Routes>,'/gigs/new');await screen.findByRole('heading',{name:'Create a gig'});await user.click(screen.getByRole('button',{name:'Create draft'}));expect(await screen.findByText('Use at least 5 characters')).toBeInTheDocument();expect(mocks.create).not.toHaveBeenCalled()});
  it('loads an owned gig into edit mode and saves allowlisted fields',async()=>{const user=userEvent.setup();mocks.get.mockImplementation(()=>response({gig:{...gig,isOwner:true}}));renderAt(<Routes><Route path="/gigs/:gigId/edit" element={<GigFormPage/>}/></Routes>,`/gigs/${gig.id}/edit`);const title=await screen.findByLabelText('Gig title');await user.clear(title);await user.type(title,'Updated student society website');await user.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(mocks.update).toHaveBeenCalledWith(gig.id,expect.objectContaining({title:'Updated student society website'})));expect(mocks.update.mock.calls[0][1]).not.toHaveProperty('ownerId');expect(mocks.update.mock.calls[0][1]).not.toHaveProperty('status')});
  it('protects create and edit routes from anonymous users',async()=>{renderAt(<Routes><Route element={<ProtectedRoute/>}><Route path="/gigs/new" element={<div>Secret create form</div>}/></Route><Route path="/login" element={<div>Login required</div>}/></Routes>,'/gigs/new',{loading:false,isAuthenticated:false});expect(await screen.findByText('Login required')).toBeInTheDocument();expect(screen.queryByText('Secret create form')).not.toBeInTheDocument()});
});
