import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { AuthContext } from '../context/auth-context.js';
import { ToastContext } from '../context/toast-context.js';
import { LoginRequiredRoute, ProtectedRoute } from '../routes/RouteGuards.jsx';
import { GigDetailsPage } from './GigDetailsPage.jsx';
import { GigFormPage } from './GigFormPage.jsx';
import { GigsPage } from './GigsPage.jsx';
import { MyGigsPage } from './MyGigsPage.jsx';
import { HomePage } from './HomePage.jsx';

const mocks=vi.hoisted(()=>({list:vi.fn(),mine:vi.fn(),get:vi.fn(),create:vi.fn(),update:vi.fn(),transition:vi.fn(),remove:vi.fn(),bookmark:vi.fn(),removeBookmark:vi.fn(),skills:vi.fn(),createSkill:vi.fn(),notify:vi.fn(),confirm:vi.fn(),loginRequired:vi.fn()}));
vi.mock('../services/api.js',()=>({gigApi:{list:mocks.list,mine:mocks.mine,get:mocks.get,create:mocks.create,update:mocks.update,transition:mocks.transition,remove:mocks.remove,bookmark:mocks.bookmark,removeBookmark:mocks.removeBookmark},skillApi:{list:mocks.skills,create:mocks.createSkill},apiError:(error)=>({status:error?.response?.status,message:error?.message||'Request failed'})}));
vi.mock('../lib/confirm-action.js',()=>({confirmAction:mocks.confirm,showLoginRequired:mocks.loginRequired}));
const skill={id:'dddddddddddddddddddddddd',name:'React',category:'Frontend'};
const gig={id:'cccccccccccccccccccccccc',title:'Build the campus society website',description:'Create an accessible responsive site for student society events.',category:'Web Development',skills:[{...skill,level:'INTERMEDIATE',required:true}],workMode:'REMOTE',locationText:'',visibility:'PLATFORM',budget:{type:'UNPAID'},deadlineAt:null,capacity:1,acceptedCount:0,proposalCount:0,acceptingProposals:true,isActive:true,status:'PUBLISHED',owner:{id:'aaaaaaaaaaaaaaaaaaaaaaaa',displayName:'Sristi Kundu'},isOwner:false,isBookmarked:false,publishedAt:new Date().toISOString(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
const auth={loading:false,isAuthenticated:true,user:{email:'student@bscse.uiu.ac.bd',profile:{displayName:'Student'}},logout:vi.fn()};
const response=(data,meta={})=>Promise.resolve({data:{data,meta}});
function renderAt(ui,path='/gigs',value=auth){return render(<MemoryRouter initialEntries={[path]}><AuthContext.Provider value={value}><ToastContext.Provider value={{notify:mocks.notify}}>{ui}</ToastContext.Provider></AuthContext.Provider></MemoryRouter>)}
beforeEach(()=>{mocks.list.mockImplementation(()=>response({gigs:[gig]},{pagination:{nextCursor:null,hasMore:false}}));mocks.mine.mockImplementation((params={})=>response({gigs:!params.status||params.status==='DRAFT'?[{...gig,status:'DRAFT',isOwner:true,acceptingProposals:false}]:[]},{pagination:{nextCursor:null,hasMore:false}}));mocks.get.mockImplementation(()=>response({gig}));mocks.skills.mockImplementation(()=>response({skills:[skill]}));mocks.createSkill.mockImplementation((body)=>response({skill:{id:'eeeeeeeeeeeeeeeeeeeeeeee',...body}}));mocks.create.mockImplementation((body)=>response({gig:{...gig,...body,status:'DRAFT'}}));mocks.update.mockImplementation((_,body)=>response({gig:{...gig,...body,isOwner:true}}));mocks.transition.mockImplementation((_,action)=>response({gig:{...gig,status:action==='publish'||action==='restore'?'PUBLISHED':'ARCHIVED',isActive:action!=='archive',isOwner:true}}));mocks.remove.mockResolvedValue({});mocks.confirm.mockResolvedValue(true);mocks.loginRequired.mockResolvedValue({});mocks.bookmark.mockResolvedValue({});mocks.removeBookmark.mockResolvedValue({})});afterEach(()=>{cleanup();vi.clearAllMocks()});

describe('Gigs Marketplace',()=>{
  it('renders server-provided gig cards',async()=>{renderAt(<GigsPage/>);expect(await screen.findByText(gig.title)).toBeInTheDocument();expect(screen.getAllByText('React').length).toBeGreaterThan(0);expect(screen.getByText('Sristi Kundu')).toBeInTheDocument()});
  it('shows the real lifecycle badge instead of treating drafts as active',async()=>{const marketplace=renderAt(<GigsPage/>);expect(await screen.findByLabelText('Gig status: Published')).toBeInTheDocument();marketplace.unmount();renderAt(<MyGigsPage/>,'/my-gigs');expect(await screen.findByLabelText('Gig status: Draft')).toBeInTheDocument();expect(screen.queryByLabelText('Gig status: Published')).not.toBeInTheDocument()});
  it('sends search and filters to the backend',async()=>{const user=userEvent.setup();renderAt(<GigsPage/>);await screen.findByText(gig.title);await user.type(screen.getByLabelText('Search gigs'),'dashboard');await user.selectOptions(screen.getByLabelText('Skill filter'),skill.id);await user.selectOptions(screen.getByLabelText('Work mode filter'),'REMOTE');await user.click(screen.getByRole('button',{name:'Apply filters'}));await waitFor(()=>expect(mocks.list).toHaveBeenLastCalledWith(expect.objectContaining({q:'dashboard',skillId:skill.id,workMode:'REMOTE'})))});
  it('bookmarks a gig and updates the visible state',async()=>{const user=userEvent.setup();renderAt(<GigsPage/>);await screen.findByText(gig.title);await user.click(screen.getByRole('button',{name:'Bookmark gig'}));await waitFor(()=>expect(mocks.bookmark).toHaveBeenCalledWith(gig.id));expect(screen.getByRole('button',{name:'Remove bookmark'})).toBeInTheDocument()});
  it('shows empty and retryable API error states',async()=>{mocks.list.mockImplementationOnce(()=>response({gigs:[]},{pagination:{hasMore:false}}));const first=renderAt(<GigsPage/>);expect(await screen.findByText('No opportunities found.')).toBeInTheDocument();first.unmount();mocks.list.mockRejectedValueOnce(new Error('Marketplace unavailable'));renderAt(<GigsPage/>);expect(await screen.findByText('Marketplace unavailable')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Try again'})).toBeInTheDocument()});
  it('renders gig details and keeps proposal functionality disabled',async()=>{renderAt(<Routes><Route path="/gigs/:gigId" element={<GigDetailsPage/>}/></Routes>,`/gigs/${gig.id}`);expect(await screen.findByRole('heading',{name:gig.title})).toBeInTheDocument();expect(screen.getByText(/About this gig/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Apply to this Gig'})).toBeDisabled()});
  it('validates the create form before calling the API',async()=>{const user=userEvent.setup();renderAt(<Routes><Route path="/gigs/new" element={<GigFormPage/>}/></Routes>,'/gigs/new');await screen.findByRole('heading',{name:'Create a gig'});await user.click(screen.getByRole('button',{name:'Create draft'}));expect(await screen.findByText('Use at least 5 characters')).toBeInTheDocument();expect(mocks.create).not.toHaveBeenCalled()});
  it('creates and automatically selects a custom gig skill',async()=>{const user=userEvent.setup();renderAt(<Routes><Route path="/gigs/new" element={<GigFormPage/>}/></Routes>,'/gigs/new');await screen.findByRole('heading',{name:'Create a gig'});await user.type(screen.getByLabelText('Custom skill name'),'Three.js');await user.type(screen.getByLabelText('Custom skill category'),'Frontend');await user.click(screen.getByRole('button',{name:'Add'}));await waitFor(()=>expect(mocks.createSkill).toHaveBeenCalledWith({name:'Three.js',category:'Frontend'}));expect(await screen.findByLabelText('Three.js required level')).toBeInTheDocument()});
  it('loads an owned gig into edit mode and saves allowlisted fields',async()=>{const user=userEvent.setup();mocks.get.mockImplementation(()=>response({gig:{...gig,isOwner:true}}));renderAt(<Routes><Route path="/gigs/:gigId/edit" element={<GigFormPage/>}/></Routes>,`/gigs/${gig.id}/edit`);const title=await screen.findByLabelText('Gig title');await user.clear(title);await user.type(title,'Updated student society website');await user.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(mocks.update).toHaveBeenCalledWith(gig.id,expect.objectContaining({title:'Updated student society website'})));expect(mocks.update.mock.calls[0][1]).not.toHaveProperty('ownerId');expect(mocks.update.mock.calls[0][1]).not.toHaveProperty('status')});
  it('protects create and edit routes from anonymous users',async()=>{renderAt(<Routes><Route element={<ProtectedRoute/>}><Route path="/gigs/new" element={<div>Secret create form</div>}/></Route><Route path="/login" element={<div>Login required</div>}/></Routes>,'/gigs/new',{loading:false,isAuthenticated:false});expect(await screen.findByText('Login required')).toBeInTheDocument();expect(screen.queryByText('Secret create form')).not.toBeInTheDocument()});
  it('uses clear labelled owner actions and confirms permanent deletion',async()=>{const user=userEvent.setup();renderAt(<MyGigsPage/>,'/my-gigs');expect(await screen.findByRole('button',{name:'Publish'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Archive'})).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Delete permanently'}));await waitFor(()=>expect(mocks.confirm).toHaveBeenCalledWith(expect.objectContaining({confirmText:'Delete permanently',danger:true})));expect(mocks.remove).toHaveBeenCalledWith(gig.id)});
  it('sends each owner status filter to the backend and shows an accurate empty state',async()=>{const user=userEvent.setup();renderAt(<MyGigsPage/>,'/my-gigs');await screen.findByLabelText('Gig status: Draft');await user.click(screen.getByRole('button',{name:'Published'}));await waitFor(()=>expect(mocks.mine).toHaveBeenLastCalledWith({status:'PUBLISHED'}));expect(await screen.findByRole('heading',{name:'No published gigs in this view'})).toBeInTheDocument()});
  it('removes a gig immediately when an action moves it outside the selected filter',async()=>{const user=userEvent.setup();renderAt(<MyGigsPage/>,'/my-gigs');await user.click(screen.getByRole('button',{name:'Draft'}));await screen.findByLabelText('Gig status: Draft');await user.click(screen.getByRole('button',{name:'Publish'}));await waitFor(()=>expect(mocks.transition).toHaveBeenCalledWith(gig.id,'publish',{}));expect(await screen.findByRole('heading',{name:'No draft gigs in this view'})).toBeInTheDocument()});
  it('restores an archived gig with its returned published lifecycle badge',async()=>{const user=userEvent.setup();mocks.mine.mockImplementation(()=>response({gigs:[{...gig,status:'ARCHIVED',isActive:false,isOwner:true}]},{pagination:{hasMore:false}}));renderAt(<MyGigsPage/>,'/my-gigs');await user.click(await screen.findByRole('button',{name:'Restore active'}));await waitFor(()=>expect(mocks.transition).toHaveBeenCalledWith(gig.id,'restore',{}));expect(await screen.findByLabelText('Gig status: Published')).toBeInTheDocument()});
  it('shows active gigs and working favourites on the homepage',async()=>{const user=userEvent.setup();renderAt(<HomePage/>,'/');expect(await screen.findByText(gig.title)).toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Bookmark gig'}));await waitFor(()=>expect(mocks.bookmark).toHaveBeenCalledWith(gig.id));expect(screen.getByRole('button',{name:'Remove bookmark'})).toBeInTheDocument()});
  it('alerts anonymous users before redirecting gig details to login',async()=>{renderAt(<Routes><Route element={<LoginRequiredRoute/>}><Route path="/gigs/:gigId" element={<div>Private gig details</div>}/></Route><Route path="/login" element={<div>Login page</div>}/></Routes>,`/gigs/${gig.id}`,{loading:false,isAuthenticated:false});await waitFor(()=>expect(mocks.loginRequired).toHaveBeenCalled());expect(await screen.findByText('Login page')).toBeInTheDocument();expect(screen.queryByText('Private gig details')).not.toBeInTheDocument()});
});
