import { AlertCircle, Archive, Eye, Pencil, Plus, Radio, XCircle } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { GigCard } from '../components/gigs/GigCard.jsx';
import { useToast } from '../context/toast-context.js';
import { AppShell } from '../layouts/AppShell.jsx';
import { apiError, gigApi } from '../services/api.js';

export function MyGigsPage(){const {notify}=useToast();const [gigs,setGigs]=useState([]);const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [pagination,setPagination]=useState({});const load=useCallback(async(cursor,append=false)=>{append||setLoading(true);setError('');try{const response=await gigApi.mine({...status?{status}:{},...cursor?{cursor}:{}});setGigs((current)=>append?[...current,...response.data.data.gigs]:response.data.data.gigs);setPagination(response.data.meta.pagination)}catch(reason){setError(apiError(reason).message)}finally{setLoading(false)}},[status]);useEffect(()=>{void load()},[load]);const transition=async(gig,action,body={})=>{const messages={publish:'Gig published.',close:'Gig closed.',cancel:'Gig cancelled.',archive:'Gig archived.'};if(!window.confirm(`${action[0].toUpperCase()+action.slice(1)} “${gig.title}”?`))return;setBusy(gig.id);try{const updated=(await gigApi.transition(gig.id,action,body)).data.data.gig;setGigs((current)=>current.map((item)=>item.id===updated.id?updated:item));notify(messages[action])}catch(reason){notify(apiError(reason).message,'error')}finally{setBusy('')}};const actions=(gig)=><>{['DRAFT','PUBLISHED'].includes(gig.status)&&<Link className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100" aria-label="Edit gig" to={`/gigs/${gig.id}/edit`}><Pencil size={16}/></Link>}{gig.status==='DRAFT'&&<button disabled={busy===gig.id} className="rounded-lg p-1.5 text-emerald-700 hover:bg-emerald-50" aria-label="Publish gig" onClick={()=>transition(gig,'publish')}><Radio size={16}/></button>}{gig.status==='PUBLISHED'&&<button disabled={busy===gig.id} className="rounded-lg p-1.5 text-amber-700 hover:bg-amber-50" aria-label="Close gig" onClick={()=>transition(gig,'close',{reasonCode:'OWNER_CLOSED'})}><XCircle size={16}/></button>}{['DRAFT','CLOSED','CANCELLED','COMPLETED'].includes(gig.status)&&<button disabled={busy===gig.id} className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100" aria-label="Archive gig" onClick={()=>transition(gig,'archive')}><Archive size={16}/></button>}</>;
  return <AppShell><div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Owner workspace</p><h1 className="mt-2 text-3xl font-bold">My Gigs</h1><p className="mt-2 text-slate-600">Manage drafts, published opportunities, and retained history.</p></div><Link className="btn-primary" to="/gigs/new"><Plus size={18}/>Create Gig</Link></div><div className="mt-6 flex flex-wrap gap-2">{['','DRAFT','PUBLISHED','CLOSED','CANCELLED','ARCHIVED'].map((value)=><button key={value||'ALL'} className={`rounded-full px-4 py-2 text-sm font-bold ${status===value?'bg-brand-600 text-white':'bg-white text-slate-600'}`} onClick={()=>setStatus(value)}>{value||'ALL'}</button>)}</div>{loading?<div className="mt-7 grid gap-5 md:grid-cols-2"><div className="h-80 animate-pulse rounded-2xl bg-slate-200"/><div className="h-80 animate-pulse rounded-2xl bg-slate-200"/></div>:error?<div className="surface mt-7 p-8 text-center"><AlertCircle className="mx-auto text-rose-600"/><p className="mt-3">{error}</p><button className="btn-primary mt-4" onClick={()=>load()}>Try again</button></div>:gigs.length===0?<div className="surface mt-7 p-10 text-center"><Eye className="mx-auto text-slate-400"/><h2 className="mt-4 text-xl font-bold">No gigs in this view</h2><p className="mt-2 text-slate-600">Create a draft or choose another lifecycle filter.</p><Link className="btn-primary mt-5" to="/gigs/new">Create your first gig</Link></div>:<><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{gigs.map((gig)=><GigCard key={gig.id} gig={gig} ownerActions={actions(gig)}/>)}</div>{pagination.hasMore&&<div className="mt-7 text-center"><button className="btn-secondary" onClick={()=>load(pagination.nextCursor,true)}>Load more</button></div>}</>}</div></AppShell>}
