import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { AuthContext } from '../context/auth-context.js';
import { ToastContext } from '../context/toast-context.js';
import { GigDetailsPage } from './GigDetailsPage.jsx';
import { GigProposalsPage } from './GigProposalsPage.jsx';
import { MyProposalsPage } from './MyProposalsPage.jsx';

const mocks=vi.hoisted(()=>({gigGet:vi.fn(),mine:vi.fn(),submit:vi.fn(),forGig:vi.fn(),shortlist:vi.fn(),accept:vi.fn(),reject:vi.fn(),notify:vi.fn(),confirm:vi.fn()}));
vi.mock('../services/api.js',()=>({gigApi:{get:mocks.gigGet},proposalApi:{mine:mocks.mine,submit:mocks.submit,forGig:mocks.forGig,shortlist:mocks.shortlist,accept:mocks.accept,reject:mocks.reject},apiError:(error)=>({status:error?.response?.status,code:error?.response?.data?.error?.code,message:error?.response?.data?.error?.message||error?.message||'Request failed'})}));
vi.mock('../lib/confirm-action.js',()=>({confirmAction:mocks.confirm}));
const GIG='cccccccccccccccccccccccc',PROPOSAL='dddddddddddddddddddddddd',APPLICANT='aaaaaaaaaaaaaaaaaaaaaaaa';
const gig={id:GIG,title:'Build an accessible student portal',description:'Create a modern accessible portal for campus student organizations.',category:'Web Development',skills:[],workMode:'REMOTE',visibility:'PLATFORM',budget:{type:'UNPAID'},deadlineAt:null,capacity:2,acceptedCount:0,proposalCount:1,acceptingProposals:true,isActive:true,status:'PUBLISHED',owner:{id:'bbbbbbbbbbbbbbbbbbbbbbbb',displayName:'Owner'},isOwner:false,isBookmarked:false,publishedAt:new Date().toISOString()};
const proposal={id:PROPOSAL,gig:{id:GIG,title:gig.title,status:'PUBLISHED',owner:gig.owner},applicant:{id:APPLICANT,displayName:'Student Applicant',headline:'Frontend developer',skills:[]},status:'SUBMITTED',currentRevisionNumber:1,currentRevision:{coverMessage:'I will build this portal with accessible and tested components.',proposedBudget:{type:'UNPAID'},proposedDuration:'Two weeks',availability:'Ten hours weekly'},submittedAt:new Date().toISOString()};
const response=(data)=>Promise.resolve({data:{data,meta:{pagination:{hasMore:false,nextCursor:null}}}});
const auth={loading:false,isAuthenticated:true,user:{id:APPLICANT,email:'student@bscse.uiu.ac.bd',profile:{displayName:'Student Applicant'}},logout:vi.fn()};
function renderAt(ui,path){return render(<MemoryRouter initialEntries={[path]}><AuthContext.Provider value={auth}><ToastContext.Provider value={{notify:mocks.notify}}>{ui}</ToastContext.Provider></AuthContext.Provider></MemoryRouter>)}
beforeEach(()=>{mocks.gigGet.mockImplementation(()=>response({gig}));mocks.mine.mockImplementation(()=>response({proposals:[]}));mocks.submit.mockImplementation((_,body)=>response({proposal:{...proposal,currentRevision:body}}));mocks.forGig.mockImplementation(()=>response({gig:{id:GIG,title:gig.title,capacity:2,acceptedCount:0},proposals:[proposal]}));mocks.shortlist.mockImplementation(()=>response({gig:{id:GIG},proposal:{...proposal,status:'SHORTLISTED'}}));mocks.accept.mockImplementation(()=>response({gig:{id:GIG,title:gig.title,capacity:2,acceptedCount:1},proposal:{...proposal,status:'ACCEPTED'}}));mocks.reject.mockImplementation(()=>response({gig:{id:GIG,title:gig.title,capacity:2,acceptedCount:0},proposal:{...proposal,status:'REJECTED'}}));mocks.confirm.mockResolvedValue(true)});afterEach(()=>{cleanup();vi.clearAllMocks()});

describe('Proposal workflow',()=>{
  it('validates and submits a proposal from an eligible gig',async()=>{const user=userEvent.setup();renderAt(<Routes><Route path="/gigs/:gigId" element={<GigDetailsPage/>}/></Routes>,`/gigs/${GIG}`);await user.click(await screen.findByRole('button',{name:'Apply to this Gig'}));await user.click(screen.getByRole('button',{name:'Submit proposal'}));expect(await screen.findByText('Write at least 20 characters')).toBeInTheDocument();await user.type(screen.getByPlaceholderText('Explain your approach, relevant experience, and why you are a strong fit.'),'I will deliver an accessible, tested portal with clear progress updates.');await user.click(screen.getByRole('button',{name:'Submit proposal'}));await waitFor(()=>expect(mocks.submit).toHaveBeenCalledWith(GIG,expect.objectContaining({coverMessage:expect.stringContaining('accessible')})));expect(await screen.findByLabelText('Proposal status: Submitted')).toBeInTheDocument()});
  it('shows an already-applied state and does not offer a duplicate form',async()=>{mocks.mine.mockImplementation(()=>response({proposals:[proposal]}));renderAt(<Routes><Route path="/gigs/:gigId" element={<GigDetailsPage/>}/></Routes>,`/gigs/${GIG}`);expect(await screen.findByText('You already submitted a proposal for this gig.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Apply to this Gig'})).not.toBeInTheDocument()});
  it('lists applicant proposals with lifecycle status and detail links',async()=>{mocks.mine.mockImplementation(()=>response({proposals:[proposal]}));renderAt(<MyProposalsPage/>,'/proposals');expect(await screen.findByRole('heading',{name:gig.title})).toBeInTheDocument();expect(screen.getByLabelText('Proposal status: Submitted')).toBeInTheDocument();expect(screen.getByRole('link',{name:/View proposal/})).toHaveAttribute('href',`/proposals/${PROPOSAL}`)});
  it('lets the owner shortlist and accept through labelled actions',async()=>{const user=userEvent.setup();renderAt(<Routes><Route path="/my-gigs/:gigId/proposals" element={<GigProposalsPage/>}/></Routes>,`/my-gigs/${GIG}/proposals`);await screen.findByText('Student Applicant');await user.click(screen.getByRole('button',{name:'Shortlist'}));await waitFor(()=>expect(mocks.shortlist).toHaveBeenCalledWith(PROPOSAL,{}));mocks.forGig.mockImplementation(()=>response({gig:{id:GIG,title:gig.title,capacity:2,acceptedCount:0},proposals:[proposal]}));cleanup();renderAt(<Routes><Route path="/my-gigs/:gigId/proposals" element={<GigProposalsPage/>}/></Routes>,`/my-gigs/${GIG}/proposals`);await user.click(await screen.findByRole('button',{name:'Accept'}));await waitFor(()=>expect(mocks.accept).toHaveBeenCalledWith(PROPOSAL,{}));expect(mocks.confirm).toHaveBeenCalledWith(expect.objectContaining({confirmText:'Accept proposal'}))});
  it('shows retryable owner API errors without leaking controls',async()=>{mocks.forGig.mockRejectedValueOnce(new Error('Review unavailable'));renderAt(<Routes><Route path="/my-gigs/:gigId/proposals" element={<GigProposalsPage/>}/></Routes>,`/my-gigs/${GIG}/proposals`);expect(await screen.findByText('Review unavailable')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Accept'})).not.toBeInTheDocument()});
});
